<a href="https://colab.research.google.com/github/NiloyKumarKundu/Graph-Neural-Network/blob/main/0_2_Graph_SAmple_aggreGatE_(GraphSAGE).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

# ---- 1. Toy graph: প্রতিটা node-এর 2-D feature ----
features = {
    "A": np.array([1.0, 0.0]),
    "B": np.array([2.0, 1.0]),
    "C": np.array([0.0, 3.0]),
    "D": np.array([4.0, 4.0]),
}

# ---- 2. শেখা weight W: concat(4-dim) -> output(2-dim), তাই shape (2,4) ----
W = np.array([
    [1.0, 0.0, 1.0, 0.0],
    [0.0, 1.0, 0.0, 1.0],
])

def relu(x):
    return np.maximum(0, x)

def graphsage_layer(target, sampled_neighbors, features, W):
    # ধাপ 1 — Aggregate: sampled neighbour-দের feature-এর mean
    neigh_feats = np.array([features[u] for u in sampled_neighbors])
    print(f"Neighbour Features \n{neigh_feats}")
    h_neigh = neigh_feats.mean(axis=0)
    print(f"mean of h_neigh: \n{h_neigh}")

    # ধাপ 2 — Combine: self + aggregated-neighbour concat, তারপর W দিয়ে project
    h_self = features[target]
    concat = np.concatenate([h_self, h_neigh])     # 4-dim
    print(f"concat: \n{concat}")
    z = W @ concat                                 # (2,4)·(4,) -> (2,)
    print(f"z: \n{z}")
    h = relu(z)                                     # nonlinearity (σ)
    print(f"h: \n{h}")

    # ধাপ 3 — L2 normalize: length 1 বানানো
    norm = np.linalg.norm(h)
    print(f"norm: \n{norm}")
    h_out = h / norm if norm > 0 else h
    return h_out

# K=2 sample ধরে {B, C}
graphsage_layer("A", ["B", "C"], features, W)

Neighbour Features 
[[2. 1.]
 [0. 3.]]
mean of h_neigh: 
[1. 2.]
concat: 
[1. 0. 1. 2.]
z: 
[2. 2.]
h: 
[2. 2.]
norm: 
2.8284271247461903


array([0.70710678, 0.70710678])