<a href="https://colab.research.google.com/github/NiloyKumarKundu/Graph-Neural-Network/blob/main/1_Basic_Graph_using_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

# ============================================================
# ধাপ ০: graph-এর কাঁচামাল — A, X
# ============================================================

# মূল adjacency matrix A (self-loop ছাড়া), ক্রম: A, B, C, D
# edge: A—B, B—C, B—D, C—D
A = np.array([
    [0, 1, 0, 0],   # A, যুক্ত: B
    [1, 0, 1, 1],   # B, যুক্ত: A, C, D
    [0, 1, 0, 1],   # C, যুক্ত: B, D
    [0, 1, 1, 0],   # D, যুক্ত: B, C
], dtype=float)
print(f"A.shape: {A.shape}")

# প্রতিটা node-এর 2টা feature
X = np.array([
    [1, 0],   # A
    [0, 1],   # B
    [1, 1],   # C
    [2, 0],   # D
], dtype=float)

# ============================================================
# ধাপ ১: self-loop যোগ করে Ã = A + I
# ============================================================
I = np.eye(A.shape[0])      # 4×4 identity matrix
A_tilde = A + I             # diagonal-এ 1 বসল → নিজের feature ধরে রাখে

# ============================================================
# ধাপ ২: degree matrix D̃ (Ã-এর প্রতিটা সারির যোগফল)
# ============================================================
degrees = A_tilde.sum(axis=1)    # প্রতিটা সারির যোগ → [2, 4, 3, 3]
D_tilde = np.diag(degrees)       # diagonal matrix বানানো

# ============================================================
# ধাপ ৩: symmetric normalization → Â = D̃^(-1/2) · Ã · D̃^(-1/2)
# ============================================================
D_inv_sqrt = np.diag(1.0 / np.sqrt(degrees))   # প্রতিটা degree-এর 1/√d
A_hat = D_inv_sqrt @ A_tilde @ D_inv_sqrt      # @ মানে matrix গুণ

# ============================================================
# ধাপ ৪: learnable weight W (এখানে fixed ধরা হলো)
# ============================================================
W = np.array([
    [2, 0],
    [0, 2],
], dtype=float)

# ============================================================
# ধাপ ৫: পুরো GCN layer → H' = σ(Â · X · W)
# ============================================================
def relu(x):
    return np.maximum(0, x)        # negative → 0, positive অপরিবর্তিত

support = A_hat @ X                 # ·X : প্রতিবেশীর তথ্য মেশানো (4×2)
transformed = support @ W          # ·W : শেখা রূপান্তর (4×2)
H_prime = relu(transformed)        # σ : nonlinearity (4×2)

# ============================================================
# ফলাফল দেখা
# ============================================================
np.set_printoptions(precision=3, suppress=True)
print(f"A = {A}")
print("Ã =\n", A_tilde)
print("degrees =", degrees)
print(f"Identidy matrix: {I}")
print("Â =\n", A_hat)
print("·X =\n", support)
print("·X·W =\n", transformed)
print("H' = ReLU(·X·W) =\n", H_prime)

A.shape: (4, 4)
A = [[0. 1. 0. 0.]
 [1. 0. 1. 1.]
 [0. 1. 0. 1.]
 [0. 1. 1. 0.]]
à =
 [[1. 1. 0. 0.]
 [1. 1. 1. 1.]
 [0. 1. 1. 1.]
 [0. 1. 1. 1.]]
degrees = [2. 4. 3. 3.]
Identidy matrix: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
 =
 [[0.5   0.354 0.    0.   ]
 [0.354 0.25  0.289 0.289]
 [0.    0.289 0.333 0.333]
 [0.    0.289 0.333 0.333]]
·X =
 [[0.5   0.354]
 [1.22  0.539]
 [1.    0.622]
 [1.    0.622]]
·X·W =
 [[1.    0.707]
 [2.439 1.077]
 [2.    1.244]
 [2.    1.244]]
H' = ReLU(·X·W) =
 [[1.    0.707]
 [2.439 1.077]
 [2.    1.244]
 [2.    1.244]]
